export APP_NGINXUI_NGINX_DIR="${EXPORTS_APP_DIR}/nginx"
export APP_NGINXUI_UI_DIR="${EXPORTS_APP_DIR}/nginx-ui"
export APP_NGINXUI_WWW_DIR="${EXPORTS_APP_DIR}/www"

# export APP_NGINXUI_UI_PORT="3123"

