version: "3.7"

services:

  server:
    image: pihole/pihole:2025.02.7@sha256:ac63178526b71aa575069945f68e7bfb57541fefcd6150d752eeae82b5638141
    # Pi-hole doesn't currently support running as non-root
    # https://github.com/pi-hole/docker-pi-hole/issues/685
    # user: "1000:1000"
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole/
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d/
    environment:
      TZ: 'Europe/Berlin'
      VIRTUAL_HOST: ${APP_DOMAIN}
      WEBPASSWORD: ${APP_PASSWORD}
      # Listen on all interfaces, permit all origins
      DNSMASQ_LISTENING: all
      WEB_PORT: 8093
    cap_add:
      - NET_ADMIN
